version: '3.8'

networks:
  database:
    internal: true
  cache:
    internal: true
  api:
    internal: true
  monit:
  proxy:

services:
  # ==================== REDIS ====================
  redis-forum-api:
    image: redis:latest
    container_name: redis-forum-api
    restart: unless-stopped
    expose:
      - 6379
    networks:
      - cache
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  # ==================== POSTGRESQL 17 ====================
  postgres-forum-api:
    image: postgres:17
    container_name: postgres-forum-api
    restart: unless-stopped
    environment:
      POSTGRES_DB: forum
      POSTGRES_USER: forum
      POSTGRES_PASSWORD: Bk55yc1u0eiqga6e
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    expose:
      - 5432
    networks:
      - database
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U forum -d forum" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - redis-forum-api
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576

  # ==================== PROMETHEUS ====================
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-forum-api
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - monit
      - api
    depends_on:
      - proxy-forum-api
    user: root

  # ==================== GRAFANA ====================
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-forum
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    networks:
      - monit
    depends_on:
      - prometheus

  # ==================== NGINX ====================
  proxy-forum-api:
    image: nginx
    container_name: proxy-forum-api
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
    ports:
      - 80:80
    networks:
      - proxy
      - api
    depends_on:
      - app-forum-api

  # ==================== APP ====================
  app-forum-api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: app-forum-api
    container_name: app-forum-api
    restart: unless-stopped
    networks:
      - api
      - database
      - cache
    depends_on:
      - postgres-forum-api
    healthcheck:
      test: "curl -sS http://app-forum-api:8080/actuator/health"
      interval: 1s
      timeout: 30s
      retries: 60
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576

#  client-forum-api:
#    build:
#      context: ./client/
#      dockerfile: Dockerfile
#    image: client-forum-api
#    container_name: client-forum-api
#    restart: unless-stopped
#    networks:
#      - proxy
#    depends_on:
#      - proxy-forum-api

volumes:
  grafana_data: